plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sars87.dashboard'
    compileSdk 35

    defaultConfig {
        applicationId 'com.sars87.dashboard'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
}
